name: task_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  get: ^4.6.6
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  logger: ^2.3.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.1
  flutter_gen: ^5.4.0
  flutter_easyloading: ^3.0.5
  shared_value: ^3.0.0
  shimmer: ^3.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/app/generate/
  line_length: 999
  parse_metadata: false

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true

  assets:
    enabled: true
    outputs:
      style: camel-case
      class_name: Assets
    exclude: []

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

