// keys for local storage
const String authTokenKey = "auth_token";
const String refreshToken = "refresh_token";
const String fcmTokenKey = "fcm_token";
const String userKey = "user";
const String languageKey = "language";
const String themeKey = "theme";
const String isIntroShownKey = "is_intro_shown";
const String secretKey = "SJWT1cGrO4aeXNvxwVMquZS2mpqVeKlDV0T";
